export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Process } from './Process'
export { default as Benefits } from './Benefits'
export { default as Services } from './Services'
export { default as Casestudies } from './Casestudies'
export { default as Contact } from './Contact'